### ISSUE TITLE
String "Setting overrides" printed randomly in terminal

### ISSUE THREAD

**Issue by tomca32** [arnstein/aws-iot-device-sdk-rust#10]
I'm making a Terminal app leveraging this crate and I randomly see the string "Setting overrides" printed in the terminal.

I've traced it to `set_overrides` function in `settings.rs`. I assume this was used for debugging purposes, but would it be possible to remove that line now if it serves no purpose?

**Comment by tomca32** [comment]
Wow nevermind...turns out somebody on our side changed the lib internally...feel free to ignore

**Comment by arnstein** [comment]
Sorry for the late reply, but glad you found it was on your side as I would have no explanation for this print in the lib 😂

**Comment by tomca32** [comment]
Yeah sorry for that, I was dumb
