### ISSUE TITLE
Unable to set max packet size

### ISSUE THREAD

**Issue by tomca32** [arnstein/aws-iot-device-sdk-rust#11]
Hey again,

I have an issue trying to change the max packet size since we tend to dump a lot of data into our packets.

The `AWSIotSettings` can take `MQTTOptionsOverrides` so I figured thats the way to do it.
`MQTTOptionsOverrides` has a field `max_packet_size` that's of a type `MQTTMaxPacketSize`.

Now the problem is that fields of `MQTTMaxPacketSize` are private and it does not have any public constructor so there is no way for me to construct an instance of `MQTTMaxPacketSize` and change the default packet size.

```rust

error[E0451]: field `outgoing_max_packet_size` of struct `MQTTMaxPacketSize` is private
  --> src/components/management_agent.rs:33:82
   |
33 |     let max_packet_size = MQTTMaxPacketSize{ icoming_max_packet_size: 1024*1024, outgoing_max_packet_size: 1024*1024 };
   |                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ private fieldd
```

Am I missing something?

**Comment by arnstein** [comment]
Thanks for pointing this out, I'll fix it tomorrow.

**Comment by arnstein** [comment]
Could you checkout the fix_maxpacketsize branch and test if it works as you want? If it does I will merge to master and create a release.

**Comment by tomca32** [comment]
Sorry for ignoring you for a few days. Will check it out today

**Comment by tomca32** [comment]
Just tested it out and it works great.

One small quality of life improvement would be to implement `default` for `MQTTOptionsOverrides` that defaults all values to `None`. That way if we need to override just one option we could write:
```rust
MQTTOptionsOverrides { 
          max_packet_size: Some(MQTTMaxPacketSize::new(1024 * 1024, 1024 * 1024)),
          ..Default::default()
```

instead of:
```rust
MQTTOptionsOverrides { 
          clean_session: None,
          keep_alive: None,
          max_packet_size: Some(MQTTMaxPacketSize::new(1024 * 1024, 1024 * 1024)),
          request_channel_capacity: None,
          pending_throttle: None,
          inflight: None,
          last_will: None,
          conn_timeout: None,
          transport: None
}
```

Thanks for your help!

**Comment by tomca32** [comment]
@arnstein I Have opened a PR based off of your branch that just adds a default derive for options overrides if that helps: https://github.com/arnstein/aws-iot-device-sdk-rust/pull/12

**Comment by arnstein** [comment]
Thanks! Will merge and make a release.
